@startuml

!include ./theme.puml

participant Jessica
participant Server
participant John

Server -> John: git clone
John -> John: git commit
Server -> Jessica: git clone
Jessica -> Jessica: git commit
Jessica -> Server: git push
Server -> John: git fetch
John -> John: git merge
John -> Server: git push
Server -> Jessica: git fetch
Jessica -> Jessica: git merge
Jessica -> Server: git push
Server -> John: git fetch

footer Figure 64. General sequence of events for\n a simple multiple-developer Git workflow

@enduml
