@startuml

<style>
document {
  FontSize 12
  FontColor #696773
  BackgroundColor #f2f2f2
}

sequenceDiagram {
  FontColor #696773

  arrow {
    FontSize 12
    LineColor #696773
  }

  participant {
    FontSize 14
    FontColor #eff1f3
    LineColor #f44d27
    BackgroundColor #f44d27
  }

  lifeLine {
    LineColor #696773
  }
}
</style>

skinparam defaultFontName JetBrains Mono
skinparam shadowing false
skinparam roundCorner 10
skinparam dpi 300

scale 600 width
scale 220 height

participant Jessica
participant Server
participant John

Server -> John: git clone
John -> John: git commit
Server -> Jessica: git clone
Jessica -> Jessica: git commit
Jessica -> Server: git push
Server -> John: git fetch
John -> John: git merge
John -> Server: git push
Server -> Jessica: git fetch
Jessica -> Jessica: git merge
Jessica -> Server: git push
Server -> John: git fetch

footer Figure 64. General sequence of events for\n a simple multiple-developer Git workflow

@enduml
